var width = 10;
var height = 5;
var area = width * height;
console.log('Value of area:', area);
console.log('typeOf area:', typeof area);
var bill = 100;
var payment = 200;
var change = payment - bill;
console.log('Value of change:', change);
console.log('typeOf change', typeof change);
var quizzes = 80;
var midterm = 90;
var final = 100;
var grade = (quizzes + midterm + final) / 3;
console.log('Value of grade:', grade);
console.log('typeOf grade:', typeof grade);
var firstName = 'Mohamad';
var lastName = 'Alsyouf';
var fullName = firstName + ' ' + lastName;
console.log('Value of fullName:', fullName);
console.log('typeOf fullName:', typeof fullName);
var ph = 3;
var isAcidic = ph < 7;
console.log('Value of isAcidic:', isAcidic);
console.log('typeOf isAcidic:', typeof isAcidic);
var headCount = 200;
var isSparta = headCount === 300;
console.log('Value of isSparta:', isSparta);
console.log('typeOf isSparta:', typeof isSparta);
var motto = fullName;
motto = fullName + ' is the GOAT';
console.log('Value of motto:', motto);
console.log('typeOf motto:', typeof motto);
